### ISSUE TITLE
meteor-ionic and meteor-angular incompatible

### ISSUE THREAD

**Issue by barbatus** [Urigo/meteor-ionic#51]
meteor-angular uses Angular 1.4 but meteor-ionic uses previous version. 
There appears bunch of exceptions if they are added together.
Can you approve this [PR] (https://github.com/Urigo/meteor-ionic/pull/49)?

**Comment by Urigo** [comment]
Thanks, I've just released 1.0.0_1 with updated dependencies, can you check this out?

**Comment by harellevy** [comment]
still having that bug, which angular-meteor version works with meteor-ionic?

**Comment by harellevy** [comment]
At the end it was working well, something messed up with meteor-bower, The dependencies was on .meteor directory even after i removed it from my bower.json, I had a conflict with ionic-meterial bower package and ionic

**Comment by Urigo** [comment]
ohhh I hate that bower package!
